name: payload-dumper-actions

on:
workflow_dispatch:
  inputs:
    rom_url:
      description: 'ROM 下载直链'
      required: true
      default: 'https://mirrorbits.lineageos.org/full/tissot/20230328/lineage-19.1-20230328-nightly-tissot-signed.zip'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install depedencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          sudo apt install aria2
          mkdir tmp
          wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.0/payload-dumper-go_1.2.0_linux_amd64.tar.gz -P tmp/
          tar zxvf ./tmp/payload-dumper-go_1.2.0_linux_amd64.tar.gz -o payload-dumper-go

      - name: Download ROM
        run: |
          aria2c -s 10 -x 10 -d . -o ./tmp/ROM.zip "${{ github.event.inputs.rom_url }}"

      - name: Dump payload.bin
        run: |
          ./payload-dumper-go -p boot -o output ./tmp/ROM.zip
          rm -rf tmp/
          rm payload-dumper-go

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: boot.img
          path: './output/boot.img'